### ISSUE TITLE
return sympy compatible model

### ISSUE THREAD

**Issue by lacava** [folivetti/ITEA#13]
hello, 

In the update to srbench, all methods need to return a sympy compatible model string. I'm having trouble parsing the one that ITEA in srbench currently returns, which is formatted as a Python expression with, e.g. `np.tanh(x[:,0])` in it. Could you clarify how to return sympy models? 

Here's a test log: https://github.com/cavalab/srbench/actions/runs/5884085024/job/15958102513

the `model()` function here needs to be updated: https://github.com/cavalab/srbench/blob/separate-envs/algorithms/itea/regressor.py

**Comment by folivetti** [comment]
Done!!
I also made a change to `regressor.py` in the srbench repo to make it work.
Sympy has two power operators `^`  and `**`. The first only supports positive integers, so any other method using power operators should print `**` instead of `^` just in case.
